/**
 * Re-export shared domain types (single source of truth).
 */
export type {
  FlightResponse,
  TripResponse,
  ScanResponse,
  DateAvecHoraire,
  Destination,
  ScanRequest,
  Airport,
  EnrichedTripResponse,
  InspireRequest,
  InspireResponse,
  SavedSearch,
  SavedFavorite,
  ApiConfig,
  TravelDeal,
  LikedDeal,
  DealProviderId,
  PlannedTrip,
  PlannedTripDetail,
  TripProposal,
    TripMember,
  CreatePlannedTripRequest,
  InvitePreview,
  PlannedTripStatus,
  TripProposalStatus,
  TripMemberStatus,
  TripMemberRole,
} from '@flightwatcher/shared'
